name: Build Status

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: go mod download
      - name: Build Server
        run: go build -v -o build/server cmd/server/main.go
      - name: Build CLI
        run: go build -v -o build/cli cmd/cli/main.go
